exports.PositiveSearchList = [ 
    "sibling",
    "councilperson",
    "anchorwoman",
    "assemblywoman",
    "bagwoman",
    "bondswoman",
    "brakewoman",
    "sistren",
    "bride's attendant",
    "sisterhood",
    "sisterly",
    "businesswoman",
    "camerawoman",
    "camerawomen",
    "cattlewomen",
    "cavewomen",
    "cavewoman",
    "chairwoman",
    "congresswoman",
    "cowgirl",
    "crewmember",
    "doorperson",
    "motherhood",
    "firewoman",
    "forebears",
    "forewoman",
    "frontwoman",
    "goddess",
    "grandmothered",
    "she",
    "her",
    "hers",
    "she's",
    "homemaker",
    "jill-of-all-trades",
    "journeywoman",
    "queen",
    "layperson",
    "lumberjill",
    "honored attendant",
    "mailwoman",
    "crewed",
    "maintenance hole",
    "womankind",
    "womanly",
    "womanmade",
    "womanpower",
    "markswoman",
    "skillful",
    "mx",
    "mx",
    "paper carrier",
    "newswoman",
    "no-woman's-land",
    "noblewoman",
    "person not included",
    "policewoman",
    "repairwoman",
    "saleswoman",
    "snowperson",
    "flight attendant",
    "meteorologist"
];

exports.PositiveDatabase = {
    "sibling": { "BonusPoints": 1 },
    "councilperson": { "BonusPoints": 1 },
    "anchorwoman": { "BonusPoints": 1 },
    "assemblywoman": { "BonusPoints": 1 },
    "bagwoman": { "BonusPoints": 1 },
    "bondswoman": { "BonusPoints": 1 },
    "brakewoman": { "BonusPoints": 1 },
    "sistren": { "BonusPoints": 2 },
    "bride's attendant": { "BonusPoints": 1 },
    "sisterhood": { "BonusPoints": 1 },
    "sisterly": { "BonusPoints": 1 },
    "businesswoman": { "BonusPoints": 1 },
    "camerawoman": { "BonusPoints": 1 },
    "camerawomen": { "BonusPoints": 1 },
    "cattlewomen": { "BonusPoints": 1 },
    "cavewomen": { "BonusPoints": 1 },
    "cavewoman": { "BonusPoints": 1 },
    "chairwoman": { "BonusPoints": 1 },
    "congresswoman": { "BonusPoints": 1 },
    "cowgirl": { "BonusPoints": 1 },
    "crewmember": { "BonusPoints": 1 },
    "doorperson": { "BonusPoints": 1 },
    "motherhood": { "BonusPoints": 1 },
    "firewoman": { "BonusPoints": 1 },
    "forebears": { "BonusPoints": 1 },
    "forewoman": { "BonusPoints": 1 },
    "frontwoman": { "BonusPoints": 1 },
    "goddess": { "BonusPoints": 1 },
    "grandmothered": { "BonusPoints": 2 },
    "she": { "BonusPoints": 1 },
    "her": { "BonusPoints": 1 },
    "hers": { "BonusPoints": 1 },
    "she's": { "BonusPoints": 1 },
    "homemaker": { "BonusPoints": 1 },
    "jill-of-all-trades": { "BonusPoints": 1 },
    "journeywoman": { "BonusPoints": 1 },
    "queen": { "BonusPoints": 1 },
    "layperson": { "BonusPoints": 1 },
    "lumberjill": { "BonusPoints": 1 },
    "honored attendant": { "BonusPoints": 1 },
    "mailwoman": { "BonusPoints": 1 },
    "crewed": { "BonusPoints": 1 },
    "maintenance hole": { "BonusPoints": 1 },
    "womankind": { "BonusPoints": 1 },
    "womanly": { "BonusPoints": 1 },
    "womanmade": { "BonusPoints": 1 },
    "womanpower": { "BonusPoints": 1 },
    "markswoman": { "BonusPoints": 1 },
    "skillful": { "BonusPoints": 1 },
    "mx": { "BonusPoints": 2 },
    "mx": { "BonusPoints": 2 },
    "paper carrier": { "BonusPoints": 1 },
    "newswoman": { "BonusPoints": 1 },
    "no-woman's-land": { "BonusPoints": 1 },
    "noblewoman": { "BonusPoints": 1 },
    "person not included": { "BonusPoints": 1 },
    "policewoman": { "BonusPoints": 1 },
    "repairwoman": { "BonusPoints": 1 },
    "saleswoman": { "BonusPoints": 1 },
    "snowperson": { "BonusPoints": 1 },
    "flight attendant": { "BonusPoints": 1 },
    "meteorologist": { "BonusPoints": 1 }
};

exports.ProblematicSearchList = [
    "brother",
    "actor",
    "stewardess",
    "airman",
    "alderman",
    "alumnus",
    "anchorman",
    "assemblyman",
    "bagboy",
    "bondsman",
    "boy",
    "brakeman",
    "brethren",
    "bridesmaid",
    "brotherhood",
    "brotherly",
    "busboy",
    "businessman",
    "cameraman",
    "cameramen",
    "cattlemen",
    "cavemen",
    "caveman",
    "chairman",
    "chambermaid",
    "coed",
    "comedienne",
    "conductress",
    "conman",
    "congressmen",
    "countryman",
    "cowboy",
    "craftsman",
    "crewman",
    "dairyman",
    "deliveryman",
    "doorman",
    "fatherhood",
    "father",
    "fatherland",
    "feisty",
    "fireman",
    "flagman",
    "flyboy",
    "forefathers",
    "foreman",
    "freshman",
    "frontman",
    "funnyman",
    "gamesmanship",
    "god",
    "grandfathered",
    "he",
    "him",
    "his",
    "he's",
    "handyman",
    "headmaster",
    "heiress",
    "helmsman",
    "henchman",
    "heroine",
    "hostess",
    "housewife",
    "infantryman",
    "jack-of-all-trades",
    "johnny-come-lately",
    "johnny-on-the-spot",
    "journeyman",
    "juryman",
    "king-size",
    "king",
    "lady",
    "ladies",
    "layman",
    "legman",
    "letterman",
    "longshoreman",
    "lumberjack",
    "maid",
    "maid-of-honor",
    "maiden",
    "mailman",
    "majorette",
    "man",
    "male",
    "manned",
    "man-sized",
    "man-to-man",
    "manageress",
    "man-eater",
    "maneater",
    "manhandle",
    "manhole",
    "man-hours",
    "mankind",
    "manly",
    "manmade",
    "manpower",
    "marksman",
    "masseuse",
    "master",
    "masterful",
    "masterpiece",
    "middleman",
    "midshipman",
    "miss",
    "mistress",
    "mr",
    "murderess",
    "newsboy",
    "newsman",
    "newspaperman",
    "no-man's-land",
    "nobleman",
    "number-one-man",
    "number-two-man",
    "oarsman",
    "odd-man-out",
    "oilman",
    "paperboy",
    "policeman",
    "penmanship",
    "pitchman",
    "playboy",
    "postman",
    "pressman",
    "repairman",
    "salesman",
    "sculptress",
    "seaman",
    "seamstress",
    "seductress",
    "shipmaster",
    "showman",
    "showmanship",
    "snowman",
    "song-and-dance-man",
    "songstress",
    "sorceress",
    "spaceman",
    "sportsmanlike",
    "starlet",
    "statesman",
    "stewardess",
    "switchman",
    "taskmaster",
    "temptress",
    "toastmaster",
    "triggerman",
    "usherette",
    "waiter",
    "waitress",
    "watchman",
    "weatherman",
    "workman",
    "workmanlike",
    "yes-man",
    "guy",
    "Abrasive",
    "Bombshell",
    "Bubbly",
    "Catty",
    "Curvy",
    "Dramatic",
    "Emotional",
    "Gossipy",
    "High-maintenance",
    "honey",
    "Humorless",
    "hunny",
    "Man-hater",
    "Nag",
    "Prude",
    "Pushy",
    "Sassy",
    "Shrew",
    "Shrill",
    "sweetheart",
    "sweetie",
    "ball-buster",
    "Banshee",
    "Bitchy",
    "bitch",
    "Bossy",
    "Bridezilla",
    "Cougar",
    "Ditzy",
    "Feminazi",
    "Frigid",
    "Frumpy",
    "Hormonal",
    "Hysterical",
    "Lippy",
    "Man-eater",
    "Mannish",
    "Slut",
    "Slutty",
    "Trollop"
];

exports.ProblematicDatabase = {
    "brother": { GNReplacement: "sibling", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "actor": { GNReplacement: "actor", FemReplacement: "actress", WarningMessage: "", ProblemPoints: 1 },
    "stewardess": { GNReplacement: "flight attendant", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "airman": { GNReplacement: "aviator", FemReplacement: "airwoman", WarningMessage: "", ProblemPoints: 1 },
    "alderman": { GNReplacement: "councilperson", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "alumnus": { GNReplacement: "graduate", FemReplacement: "alumna", WarningMessage: "", ProblemPoints: 1 },
    "anchorman": { GNReplacement: "anchor", FemReplacement: "anchorwoman", WarningMessage: "", ProblemPoints: 1 },
    "assemblyman": { GNReplacement: "assemblyperson", FemReplacement: "assemblywoman", WarningMessage: "", ProblemPoints: 1 },
    "bagboy": { GNReplacement: "bagger", FemReplacement: "bagwoman", WarningMessage: "", ProblemPoints: 1 },
    "bondsman": { GNReplacement: "bondsperson", FemReplacement: "bondswoman", WarningMessage: "", ProblemPoints: 1 },
    "boy": { GNReplacement: "child", FemReplacement: "girl", WarningMessage: "", ProblemPoints: 0 },
    "brakeman": { GNReplacement: "brake operator", FemReplacement: "brakewoman", WarningMessage: "", ProblemPoints: 1 },
    "brethren": { GNReplacement: "laity", FemReplacement: "sistren", WarningMessage: "", ProblemPoints: 1 },
    "bridesmaid": { GNReplacement: "bride's attendant", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "brotherhood": { GNReplacement: "fellowship", FemReplacement: "sisterhood", WarningMessage: "", ProblemPoints: 1 },
    "brotherly": { GNReplacement: "kind", FemReplacement: "sisterly", WarningMessage: "", ProblemPoints: 1 },
    "busboy": { GNReplacement: "table attendant", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "businessman": { GNReplacement: "businessperson", FemReplacement: "businesswoman", WarningMessage: "", ProblemPoints: 1 },
    "cameraman": { GNReplacement: "camera operator", FemReplacement: "camerawoman", WarningMessage: "", ProblemPoints: 1 },
    "cameramen": { GNReplacement: "camera operator", FemReplacement: "camerawomen", WarningMessage: "", ProblemPoints: 1 },
    "cattlemen": { GNReplacement: "cattle owners", FemReplacement: "cattlewomen", WarningMessage: "", ProblemPoints: 1 },
    "cavemen": { GNReplacement: "cave dwellers", FemReplacement: "cavewomen", WarningMessage: "", ProblemPoints: 1 },
    "caveman": { GNReplacement: "cave dweller", FemReplacement: "cavewoman", WarningMessage: "", ProblemPoints: 1 },
    "chairman": { GNReplacement: "chair", FemReplacement: "chairwoman", WarningMessage: "", ProblemPoints: 1 },
    "chambermaid": { GNReplacement: "housekeeper", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "coed": { GNReplacement: "student", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "comedienne": { GNReplacement: "comedian", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "conductress": { GNReplacement: "conductor", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "conman": { GNReplacement: "swindler", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "congressmen": { GNReplacement: "congressperson", FemReplacement: "congresswoman", WarningMessage: "", ProblemPoints: 1 },
    "countryman": { GNReplacement: "compatriot", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "cowboy": { GNReplacement: "cowhand", FemReplacement: "cowgirl", WarningMessage: "", ProblemPoints: 1 },
    "craftsman": { GNReplacement: "artisan", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "crewman": { GNReplacement: "crewmember", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "dairyman": { GNReplacement: "dairy farmer", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "deliveryman": { GNReplacement: "courier", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "doorman": { GNReplacement: "doorperson", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "fatherhood": { GNReplacement: "parenthood", FemReplacement: "motherhood", WarningMessage: "", ProblemPoints: 1 },
    "father": { GNReplacement: "parent", FemReplacement: "mother", WarningMessage: "", ProblemPoints: 0 },
    "fatherland": { GNReplacement: "homeland", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "feisty": { GNReplacement: "energetic", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "fireman": { GNReplacement: "firefighter", FemReplacement: "firewoman", WarningMessage: "", ProblemPoints: 1 },
    "flagman": { GNReplacement: "flagger", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "flyboy": { GNReplacement: "pilot", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "forefathers": { GNReplacement: "forebears", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "foreman": { GNReplacement: "supervisor", FemReplacement: "forewoman", WarningMessage: "", ProblemPoints: 1 },
    "freshman": { GNReplacement: "first-year student", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "frontman": { GNReplacement: "frontperson", FemReplacement: "frontwoman", WarningMessage: "", ProblemPoints: 1 },
    "funnyman": { GNReplacement: "comedian", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "gamesmanship": { GNReplacement: "game playing", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "god": { GNReplacement: "deity", FemReplacement: "goddess", WarningMessage: "", ProblemPoints: 1 },
    "grandfathered": { GNReplacement: "grandparented", FemReplacement: "grandmothered", WarningMessage: "", ProblemPoints: 1 },
    "he": { GNReplacement: "they", FemReplacement: "she", WarningMessage: "", ProblemPoints: 0 },
    "him": { GNReplacement: "them", FemReplacement: "her", WarningMessage: "", ProblemPoints: 0 },
    "his": { GNReplacement: "theirs", FemReplacement: "hers", WarningMessage: "", ProblemPoints: 0 },
    "he's": { GNReplacement: "they're", FemReplacement: "she's", WarningMessage: "", ProblemPoints: 0 },
    "handyman": { GNReplacement: "fixer", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "headmaster": { GNReplacement: "principal", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "heiress": { GNReplacement: "heir", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "helmsman": { GNReplacement: "coxswain", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "henchman": { GNReplacement: "partner in crime", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "heroine": { GNReplacement: "hero", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "hostess": { GNReplacement: "host", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "housewife": { GNReplacement: "homemaker", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "infantryman": { GNReplacement: "infantry soldier", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "jack-of-all-trades": { GNReplacement: "handyperson", FemReplacement: "jill-of-all-trades", WarningMessage: "", ProblemPoints: 1 },
    "johnny-come-lately": { GNReplacement: "newcomer", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "johnny-on-the-spot": { GNReplacement: "prompt person", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "journeyman": { GNReplacement: "experienced tradesperson", FemReplacement: "journeywoman", WarningMessage: "", ProblemPoints: 1 },
    "juryman": { GNReplacement: "juror", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "king-size": { GNReplacement: "huge", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "king": { GNReplacement: "monarch", FemReplacement: "queen", WarningMessage: "", ProblemPoints: 0 },
    "lady": { GNReplacement: "", FemReplacement: "woman", WarningMessage: "", ProblemPoints: 1 },
    "ladies": { GNReplacement: "", FemReplacement: "women", WarningMessage: "", ProblemPoints: 1 },
    "layman": { GNReplacement: "layperson", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "legman": { GNReplacement: "runner", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "letterman": { GNReplacement: "athlete", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "longshoreman": { GNReplacement: "stevedore", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "lumberjack": { GNReplacement: "logger", FemReplacement: "lumberjill", WarningMessage: "", ProblemPoints: 1 },
    "maid": { GNReplacement: "house cleaner", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "maid-of-honor": { GNReplacement: "honored attendant", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "maiden": { GNReplacement: "initial", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "mailman": { GNReplacement: "mail carrier", FemReplacement: "mailwoman", WarningMessage: "", ProblemPoints: 1 },
    "majorette": { GNReplacement: "drum major", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "man": { GNReplacement: "person", FemReplacement: "woman", WarningMessage: "", ProblemPoints: 0 },
    "male": { GNReplacement: "human", FemReplacement: "female", WarningMessage: "", ProblemPoints: 0 },
    "manned": { GNReplacement: "crewed", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "man-sized": { GNReplacement: "large", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "man-to-man": { GNReplacement: "face-to-face", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "manageress": { GNReplacement: "manager", FemReplacement: "", WarningMessage: "", ProblemPoints: 5 },
    "man-eater": { GNReplacement: "flesh eater", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "maneater": { GNReplacement: "flesh eater", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "manhandle": { GNReplacement: "rough up", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "manhole": { GNReplacement: "maintenance hole", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "man-hours": { GNReplacement: "work hours", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "mankind": { GNReplacement: "humankind", FemReplacement: "womankind", WarningMessage: "", ProblemPoints: 1 },
    "manly": { GNReplacement: "humanlike", FemReplacement: "womanly", WarningMessage: "", ProblemPoints: 2 },
    "manmade": { GNReplacement: "handmade", FemReplacement: "womanmade", WarningMessage: "", ProblemPoints: 1 },
    "manpower": { GNReplacement: "workforce", FemReplacement: "womanpower", WarningMessage: "", ProblemPoints: 1 },
    "marksman": { GNReplacement: "sharpshooter", FemReplacement: "markswoman", WarningMessage: "", ProblemPoints: 1 },
    "masseuse": { GNReplacement: "massage therapist", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "master": { GNReplacement: "expert", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "masterful": { GNReplacement: "skillful", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "masterpiece": { GNReplacement: "great work of art", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "middleman": { GNReplacement: "intermediary", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "midshipman": { GNReplacement: "sailor", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "miss": { GNReplacement: "mx", FemReplacement: "", WarningMessage: "", ProblemPoints: 3 },
    "mistress": { GNReplacement: "companion", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "mr": { GNReplacement: "mx", FemReplacement: "", WarningMessage: "", ProblemPoints: 0 },
    "murderess": { GNReplacement: "murderer", FemReplacement: "", WarningMessage: "", ProblemPoints: 5 },
    "newsboy": { GNReplacement: "paper carrier", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "newsman": { GNReplacement: "reporter", FemReplacement: "newswoman", WarningMessage: "", ProblemPoints: 2 },
    "newspaperman": { GNReplacement: "journalist", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "no-man's-land": { GNReplacement: "uninhabited land", FemReplacement: "no-woman's-land", WarningMessage: "", ProblemPoints: 1 },
    "nobleman": { GNReplacement: "noble person", FemReplacement: "noblewoman", WarningMessage: "", ProblemPoints: 1 },
    "number-one-man": { GNReplacement: "leader", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "number-two-man": { GNReplacement: "second in command", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "oarsman": { GNReplacement: "rower", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "odd-man-out": { GNReplacement: "person not included", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "oilman": { GNReplacement: "oil executive", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "paperboy": { GNReplacement: "paper carrier", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "policeman": { GNReplacement: "police officer", FemReplacement: "policewoman", WarningMessage: "", ProblemPoints: 1 },
    "penmanship": { GNReplacement: "handwriting", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "pitchman": { GNReplacement: "promoter", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "playboy": { GNReplacement: "carouser", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "postman": { GNReplacement: "letter carrier", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "pressman": { GNReplacement: "press operator", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "repairman": { GNReplacement: "repairperson", FemReplacement: "repairwoman", WarningMessage: "", ProblemPoints: 1 },
    "salesman": { GNReplacement: "salesperson", FemReplacement: "saleswoman", WarningMessage: "", ProblemPoints: 1 },
    "sculptress": { GNReplacement: "sculptor", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "seaman": { GNReplacement: "sailor", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "seamstress": { GNReplacement: "tailor", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "seductress": { GNReplacement: "seducer", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "shipmaster": { GNReplacement: "captain", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "showman": { GNReplacement: "performer", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "showmanship": { GNReplacement: "stage presence", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "snowman": { GNReplacement: "snowperson", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "song-and-dance-man": { GNReplacement: "singer and dancer", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "songstress": { GNReplacement: "singer", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "sorceress": { GNReplacement: "sorcerer", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "spaceman": { GNReplacement: "astronaut", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "sportsmanlike": { GNReplacement: "sporting", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "starlet": { GNReplacement: "star", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "statesman": { GNReplacement: "politician", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "stewardess": { GNReplacement: "flight attendant", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "switchman": { GNReplacement: "switch operator", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "taskmaster": { GNReplacement: "supervisor", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "temptress": { GNReplacement: "enticer", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "toastmaster": { GNReplacement: "toast maker", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "triggerman": { GNReplacement: "shooter", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "usherette": { GNReplacement: "usher", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "waiter": { GNReplacement: "server", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "waitress": { GNReplacement: "server", FemReplacement: "", WarningMessage: "", ProblemPoints: 2 },
    "watchman": { GNReplacement: "security guard", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "weatherman": { GNReplacement: "meteorologist", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "workman": { GNReplacement: "worker", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "workmanlike": { GNReplacement: "skillful", FemReplacement: "", WarningMessage: "", ProblemPoints: 1 },
    "yes-man": { GNReplacement: "sycophant", FemReplacement: "yes-woman", WarningMessage: "", ProblemPoints: 1 },
    "guy": { GNReplacement: "person", FemReplacement: "gal", WarningMessage: "", ProblemPoints: 2 },
    "Abrasive": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Abrasive', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Bombshell": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Bombshell', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Bubbly": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Bubbly', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Catty": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Catty', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Curvy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Curvy', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Dramatic": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Dramatic', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Emotional": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Emotional', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Gossipy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Gossipy', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "High-maintenance": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'High-maintenance', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "honey": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'honey', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Humorless": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Humorless', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "hunny": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'hunny', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Man-hater": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Man-hater', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Nag": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Nag', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Prude": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Prude', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Pushy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Pushy', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Sassy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Sassy', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Shrew": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Shrew', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "Shrill": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Shrill', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "sweetheart": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'sweetheart', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "sweetie": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'sweetie', is generally considered offensive in a gendered context. You should re-word this before using this text.", ProblemPoints: 50 },
    "ball-buster": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'ball-buster', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Banshee": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Banshee', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Bitchy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Bitchy', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "bitch": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'bitch', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Bossy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Bossy', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Bridezilla": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Bridezilla', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Cougar": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Cougar', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Ditzy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Ditzy', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Feminazi": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Feminazi', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Frigid": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Frigid', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Frumpy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Frumpy', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Hormonal": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Hormonal', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Hysterical": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Hysterical', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Lippy": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Lippy', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Man-eater": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Man-eater', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Mannish": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Mannish', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Slut": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Slut', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Slutty": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Slutty', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 },
    "Trollop": { GNReplacement: "", FemReplacement: "", WarningMessage: "The term 'Trollop', is generally offensive, you should not send this text to anyone before removing it.", ProblemPoints: 999999999 }
};